# Curl request mock:
# curl 'http://localhost:5000/register' -X POST -H 'Accept: */*' -H 'Content-Type: application/json' --data-raw '{"gamertag":"theball","email":"mcihme@gmail.com","password":"1234","age":"18","description":"a"}'
register:
	curl 'http://localhost:5000/register' -X POST -H 'Accept: */*' -H 'Content-Type: application/json' --data-raw '{"gamertag":"theball","email":"mcihme@gmail.com","password":"1234","age":"18","description":"a"}'